<?php $this->headScript()->captureStart();?>
$(function () {
	$('.tooltipMe').tooltip({placement:'bottom'});
});
<?php $this->headScript()->captureEnd();?>

<div class="container" style="margin-top: 60px;margin-bottom: 15px;">
	<h4 style="font-family: Open sans;font-weight: lighter;float: left;color: #969696;">Tell us with who do you desire to bang...</h4>
	<form class="navbar-search pull-right">
	  <input type="text" class="search-query" placeholder="Search a sex symbol">
	</form>
	<a class="filter dropdown-toggle" data-toggle="dropdown" href="#">
    Filter
  </a>
  <ul class="dropdown-menu">
  	<li><a href="#">All</a></li>
    <li><a href="#">Men</a></li>
    <li><a href="#">Women</a></li>
    <li><a href="#">Cougars</a></li>
    <li><a href="#">Silver fox</a></li>
  </ul>
</div>
<div class="container">	
	<div class="row-fluid">
		<div class="span3">
			<div class="friend">
				<img src="/img/ali.jpg" class="pic"/>
				<div class="layer"></div>
				<p>Alicia Db</p>
				<div class="action">
					<a class="new" href="#fuckit" data-id="505483843">
			      Down to Bang
			    </a>
				</div>
			</div>
		</div>
		<div class="span3">
			<div class="friend">
				<img src="/img/caro.jpg" class="pic"/>
				<p>Caro Nihoul</p>
				<div class="action">
					<a class="new" href="#fuckit" data-id="505483843">
			      Down to Bang
			    </a>
				</div>
			</div>
		</div>
		<div class="span3">
			<div class="friend">
				<img src="/img/olivia.jpg" class="pic"/>
				<p>Olivia Orban</p>
				<div class="action">
					<a class="wait" href="#fuckit" data-id="505483843">
			      Awaitting to Bang
			    </a>
				</div>
			</div>
		</div>
		<div class="span3">
			<div class="friend">
				<img src="/img/tessa.jpg" class="pic"/>
				<p>Tessa Doornart</p>
				<div class="action">
					<a class="new" href="#fuckit" data-id="505483843">
			      Down to Bang
			    </a>
				</div>
			</div>
		</div>
	</div>
</div>	